# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Application(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'int',
        'application_name': 'str'
    }

    attribute_map = {
        'application_id': 'applicationId',
        'application_name': 'applicationName'
    }

    def __init__(self, application_id=None, application_name=None):  # noqa: E501
        """Application - a model defined in Swagger"""  # noqa: E501

        self._application_id = None
        self._application_name = None
        self.discriminator = None

        if application_id is not None:
            self.application_id = application_id
        self.application_name = application_name

    @property
    def application_id(self):
        """Gets the application_id of this Application.  # noqa: E501

        The ID of the application. This will be generated by the Masking Engine.  # noqa: E501

        :return: The application_id of this Application.  # noqa: E501
        :rtype: int
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this Application.

        The ID of the application. This will be generated by the Masking Engine.  # noqa: E501

        :param application_id: The application_id of this Application.  # noqa: E501
        :type: int
        """

        self._application_id = application_id

    @property
    def application_name(self):
        """Gets the application_name of this Application.  # noqa: E501

        The name of this Application. Note that it must be unique.  # noqa: E501

        :return: The application_name of this Application.  # noqa: E501
        :rtype: str
        """
        return self._application_name

    @application_name.setter
    def application_name(self, application_name):
        """Sets the application_name of this Application.

        The name of this Application. Note that it must be unique.  # noqa: E501

        :param application_name: The application_name of this Application.  # noqa: E501
        :type: str
        """
        if application_name is None:
            raise ValueError("Invalid value for `application_name`, must not be `None`")  # noqa: E501
        if application_name is not None and len(application_name) > 100:
            raise ValueError("Invalid value for `application_name`, length must be less than or equal to `100`")  # noqa: E501

        self._application_name = application_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Application, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Application):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
