# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApplicationSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'setting_id': 'int',
        'setting_group': 'str',
        'setting_name': 'str',
        'setting_value': 'str'
    }

    attribute_map = {
        'setting_id': 'settingId',
        'setting_group': 'settingGroup',
        'setting_name': 'settingName',
        'setting_value': 'settingValue'
    }

    def __init__(self, setting_id=None, setting_group=None, setting_name=None, setting_value=None):  # noqa: E501
        """ApplicationSettings - a model defined in Swagger"""  # noqa: E501

        self._setting_id = None
        self._setting_group = None
        self._setting_name = None
        self._setting_value = None
        self.discriminator = None

        if setting_id is not None:
            self.setting_id = setting_id
        if setting_group is not None:
            self.setting_group = setting_group
        if setting_name is not None:
            self.setting_name = setting_name
        self.setting_value = setting_value

    @property
    def setting_id(self):
        """Gets the setting_id of this ApplicationSettings.  # noqa: E501

        The ID of the application setting  # noqa: E501

        :return: The setting_id of this ApplicationSettings.  # noqa: E501
        :rtype: int
        """
        return self._setting_id

    @setting_id.setter
    def setting_id(self, setting_id):
        """Sets the setting_id of this ApplicationSettings.

        The ID of the application setting  # noqa: E501

        :param setting_id: The setting_id of this ApplicationSettings.  # noqa: E501
        :type: int
        """

        self._setting_id = setting_id

    @property
    def setting_group(self):
        """Gets the setting_group of this ApplicationSettings.  # noqa: E501

        Application setting group  # noqa: E501

        :return: The setting_group of this ApplicationSettings.  # noqa: E501
        :rtype: str
        """
        return self._setting_group

    @setting_group.setter
    def setting_group(self, setting_group):
        """Sets the setting_group of this ApplicationSettings.

        Application setting group  # noqa: E501

        :param setting_group: The setting_group of this ApplicationSettings.  # noqa: E501
        :type: str
        """
        if setting_group is not None and len(setting_group) > 255:
            raise ValueError("Invalid value for `setting_group`, length must be less than or equal to `255`")  # noqa: E501

        self._setting_group = setting_group

    @property
    def setting_name(self):
        """Gets the setting_name of this ApplicationSettings.  # noqa: E501

        Application setting available per group  # noqa: E501

        :return: The setting_name of this ApplicationSettings.  # noqa: E501
        :rtype: str
        """
        return self._setting_name

    @setting_name.setter
    def setting_name(self, setting_name):
        """Sets the setting_name of this ApplicationSettings.

        Application setting available per group  # noqa: E501

        :param setting_name: The setting_name of this ApplicationSettings.  # noqa: E501
        :type: str
        """
        if setting_name is not None and len(setting_name) > 255:
            raise ValueError("Invalid value for `setting_name`, length must be less than or equal to `255`")  # noqa: E501

        self._setting_name = setting_name

    @property
    def setting_value(self):
        """Gets the setting_value of this ApplicationSettings.  # noqa: E501

        Value for an application setting  # noqa: E501

        :return: The setting_value of this ApplicationSettings.  # noqa: E501
        :rtype: str
        """
        return self._setting_value

    @setting_value.setter
    def setting_value(self, setting_value):
        """Sets the setting_value of this ApplicationSettings.

        Value for an application setting  # noqa: E501

        :param setting_value: The setting_value of this ApplicationSettings.  # noqa: E501
        :type: str
        """
        if setting_value is None:
            raise ValueError("Invalid value for `setting_value`, must not be `None`")  # noqa: E501
        if setting_value is not None and len(setting_value) > 255:
            raise ValueError("Invalid value for `setting_value`, length must be less than or equal to `255`")  # noqa: E501

        self._setting_value = setting_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
