# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BreakpointInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'breakpoint_type': 'str',
        'reference': 'str',
        'timeout': 'int',
        'remaining_skip_count': 'int'
    }

    attribute_map = {
        'uuid': 'uuid',
        'breakpoint_type': 'breakpointType',
        'reference': 'reference',
        'timeout': 'timeout',
        'remaining_skip_count': 'remainingSkipCount'
    }

    def __init__(self, uuid=None, breakpoint_type=None, reference=None, timeout=None, remaining_skip_count=None):  # noqa: E501
        """BreakpointInstance - a model defined in Swagger"""  # noqa: E501

        self._uuid = None
        self._breakpoint_type = None
        self._reference = None
        self._timeout = None
        self._remaining_skip_count = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if breakpoint_type is not None:
            self.breakpoint_type = breakpoint_type
        if reference is not None:
            self.reference = reference
        if timeout is not None:
            self.timeout = timeout
        if remaining_skip_count is not None:
            self.remaining_skip_count = remaining_skip_count

    @property
    def uuid(self):
        """Gets the uuid of this BreakpointInstance.  # noqa: E501

        The ID of the BreakpointInstance. This field will be generated by the Masking Engine.  # noqa: E501

        :return: The uuid of this BreakpointInstance.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this BreakpointInstance.

        The ID of the BreakpointInstance. This field will be generated by the Masking Engine.  # noqa: E501

        :param uuid: The uuid of this BreakpointInstance.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def breakpoint_type(self):
        """Gets the breakpoint_type of this BreakpointInstance.  # noqa: E501

        The breakpoint type for which to get breakpoints.  # noqa: E501

        :return: The breakpoint_type of this BreakpointInstance.  # noqa: E501
        :rtype: str
        """
        return self._breakpoint_type

    @breakpoint_type.setter
    def breakpoint_type(self, breakpoint_type):
        """Sets the breakpoint_type of this BreakpointInstance.

        The breakpoint type for which to get breakpoints.  # noqa: E501

        :param breakpoint_type: The breakpoint_type of this BreakpointInstance.  # noqa: E501
        :type: str
        """
        allowed_values = ["EXECUTION_MASK_END", "EXECUTION_MASK_PRE_KETTLE", "EXECUTION_PROFILE_COLUMN_PRE", "EXECUTION_PROFILE_DATA_PRE_KETTLE", "EXECUTION_PROFILE_END", "PROGRESS_REPORTER_POST_UPDATE", "PROGRESS_REPORTER_REMOVE_POST_LOCK", "PROGRESS_REPORTER_REMOVE_PRE_LOCK", "PROGRESS_REPORTER_UPDATE_POST_LOCK", "PROGRESS_REPORTER_UPDATE_PRE_LOCK", "RULESET_BULK_UPDATE_POST_TABLE_SAVE", "RULESET_BULK_UPDATE_POST_TABLE_UPDATE", "RULESET_BULK_UPDATE_START"]  # noqa: E501
        if breakpoint_type not in allowed_values:
            raise ValueError(
                "Invalid value for `breakpoint_type` ({0}), must be one of {1}"  # noqa: E501
                .format(breakpoint_type, allowed_values)
            )

        self._breakpoint_type = breakpoint_type

    @property
    def reference(self):
        """Gets the reference of this BreakpointInstance.  # noqa: E501

        The reference for the BreakpointInstance. An example of a reference is the async task ID for a RULESET_REFRESH operation.  # noqa: E501

        :return: The reference of this BreakpointInstance.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this BreakpointInstance.

        The reference for the BreakpointInstance. An example of a reference is the async task ID for a RULESET_REFRESH operation.  # noqa: E501

        :param reference: The reference of this BreakpointInstance.  # noqa: E501
        :type: str
        """

        self._reference = reference

    @property
    def timeout(self):
        """Gets the timeout of this BreakpointInstance.  # noqa: E501

        The number of seconds to wait at the breakpoint before timing out.  # noqa: E501

        :return: The timeout of this BreakpointInstance.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this BreakpointInstance.

        The number of seconds to wait at the breakpoint before timing out.  # noqa: E501

        :param timeout: The timeout of this BreakpointInstance.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    @property
    def remaining_skip_count(self):
        """Gets the remaining_skip_count of this BreakpointInstance.  # noqa: E501

        The number of times to pass this breakpoint before waiting on it.  # noqa: E501

        :return: The remaining_skip_count of this BreakpointInstance.  # noqa: E501
        :rtype: int
        """
        return self._remaining_skip_count

    @remaining_skip_count.setter
    def remaining_skip_count(self, remaining_skip_count):
        """Sets the remaining_skip_count of this BreakpointInstance.

        The number of times to pass this breakpoint before waiting on it.  # noqa: E501

        :param remaining_skip_count: The remaining_skip_count of this BreakpointInstance.  # noqa: E501
        :type: int
        """

        self._remaining_skip_count = remaining_skip_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BreakpointInstance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BreakpointInstance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
