# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExportResponseMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'export_host': 'str',
        'export_date': 'str',
        'requested_object_list': 'list[ExportObjectMetadata]',
        'exported_object_list': 'list[ExportObjectMetadata]'
    }

    attribute_map = {
        'export_host': 'exportHost',
        'export_date': 'exportDate',
        'requested_object_list': 'requestedObjectList',
        'exported_object_list': 'exportedObjectList'
    }

    def __init__(self, export_host=None, export_date=None, requested_object_list=None, exported_object_list=None):  # noqa: E501
        """ExportResponseMetadata - a model defined in Swagger"""  # noqa: E501

        self._export_host = None
        self._export_date = None
        self._requested_object_list = None
        self._exported_object_list = None
        self.discriminator = None

        if export_host is not None:
            self.export_host = export_host
        if export_date is not None:
            self.export_date = export_date
        if requested_object_list is not None:
            self.requested_object_list = requested_object_list
        if exported_object_list is not None:
            self.exported_object_list = exported_object_list

    @property
    def export_host(self):
        """Gets the export_host of this ExportResponseMetadata.  # noqa: E501


        :return: The export_host of this ExportResponseMetadata.  # noqa: E501
        :rtype: str
        """
        return self._export_host

    @export_host.setter
    def export_host(self, export_host):
        """Sets the export_host of this ExportResponseMetadata.


        :param export_host: The export_host of this ExportResponseMetadata.  # noqa: E501
        :type: str
        """

        self._export_host = export_host

    @property
    def export_date(self):
        """Gets the export_date of this ExportResponseMetadata.  # noqa: E501


        :return: The export_date of this ExportResponseMetadata.  # noqa: E501
        :rtype: str
        """
        return self._export_date

    @export_date.setter
    def export_date(self, export_date):
        """Sets the export_date of this ExportResponseMetadata.


        :param export_date: The export_date of this ExportResponseMetadata.  # noqa: E501
        :type: str
        """

        self._export_date = export_date

    @property
    def requested_object_list(self):
        """Gets the requested_object_list of this ExportResponseMetadata.  # noqa: E501


        :return: The requested_object_list of this ExportResponseMetadata.  # noqa: E501
        :rtype: list[ExportObjectMetadata]
        """
        return self._requested_object_list

    @requested_object_list.setter
    def requested_object_list(self, requested_object_list):
        """Sets the requested_object_list of this ExportResponseMetadata.


        :param requested_object_list: The requested_object_list of this ExportResponseMetadata.  # noqa: E501
        :type: list[ExportObjectMetadata]
        """

        self._requested_object_list = requested_object_list

    @property
    def exported_object_list(self):
        """Gets the exported_object_list of this ExportResponseMetadata.  # noqa: E501


        :return: The exported_object_list of this ExportResponseMetadata.  # noqa: E501
        :rtype: list[ExportObjectMetadata]
        """
        return self._exported_object_list

    @exported_object_list.setter
    def exported_object_list(self, exported_object_list):
        """Sets the exported_object_list of this ExportResponseMetadata.


        :param exported_object_list: The exported_object_list of this ExportResponseMetadata.  # noqa: E501
        :type: list[ExportObjectMetadata]
        """

        self._exported_object_list = exported_object_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExportResponseMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExportResponseMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
