# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FileFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_format_id': 'int',
        'file_format_name': 'str',
        'file_format_type': 'str',
        'header': 'int',
        'footer': 'int'
    }

    attribute_map = {
        'file_format_id': 'fileFormatId',
        'file_format_name': 'fileFormatName',
        'file_format_type': 'fileFormatType',
        'header': 'header',
        'footer': 'footer'
    }

    def __init__(self, file_format_id=None, file_format_name=None, file_format_type=None, header=None, footer=None):  # noqa: E501
        """FileFormat - a model defined in Swagger"""  # noqa: E501

        self._file_format_id = None
        self._file_format_name = None
        self._file_format_type = None
        self._header = None
        self._footer = None
        self.discriminator = None

        if file_format_id is not None:
            self.file_format_id = file_format_id
        if file_format_name is not None:
            self.file_format_name = file_format_name
        if file_format_type is not None:
            self.file_format_type = file_format_type
        if header is not None:
            self.header = header
        if footer is not None:
            self.footer = footer

    @property
    def file_format_id(self):
        """Gets the file_format_id of this FileFormat.  # noqa: E501

        The ID number of the file format. This field is auto-generated by the Masking Engine.  # noqa: E501

        :return: The file_format_id of this FileFormat.  # noqa: E501
        :rtype: int
        """
        return self._file_format_id

    @file_format_id.setter
    def file_format_id(self, file_format_id):
        """Sets the file_format_id of this FileFormat.

        The ID number of the file format. This field is auto-generated by the Masking Engine.  # noqa: E501

        :param file_format_id: The file_format_id of this FileFormat.  # noqa: E501
        :type: int
        """

        self._file_format_id = file_format_id

    @property
    def file_format_name(self):
        """Gets the file_format_name of this FileFormat.  # noqa: E501

        The name of the file format, as inferred from the uploaded file.  # noqa: E501

        :return: The file_format_name of this FileFormat.  # noqa: E501
        :rtype: str
        """
        return self._file_format_name

    @file_format_name.setter
    def file_format_name(self, file_format_name):
        """Sets the file_format_name of this FileFormat.

        The name of the file format, as inferred from the uploaded file.  # noqa: E501

        :param file_format_name: The file_format_name of this FileFormat.  # noqa: E501
        :type: str
        """
        if file_format_name is not None and len(file_format_name) > 100:
            raise ValueError("Invalid value for `file_format_name`, length must be less than or equal to `100`")  # noqa: E501

        self._file_format_name = file_format_name

    @property
    def file_format_type(self):
        """Gets the file_format_type of this FileFormat.  # noqa: E501

        The type of file that this file format describes.  # noqa: E501

        :return: The file_format_type of this FileFormat.  # noqa: E501
        :rtype: str
        """
        return self._file_format_type

    @file_format_type.setter
    def file_format_type(self, file_format_type):
        """Sets the file_format_type of this FileFormat.

        The type of file that this file format describes.  # noqa: E501

        :param file_format_type: The file_format_type of this FileFormat.  # noqa: E501
        :type: str
        """
        allowed_values = ["DELIMITED", "FIXED_WIDTH", "XML"]  # noqa: E501
        if file_format_type not in allowed_values:
            raise ValueError(
                "Invalid value for `file_format_type` ({0}), must be one of {1}"  # noqa: E501
                .format(file_format_type, allowed_values)
            )

        self._file_format_type = file_format_type

    @property
    def header(self):
        """Gets the header of this FileFormat.  # noqa: E501

        The number of lines at the beginning of the file to skip.  # noqa: E501

        :return: The header of this FileFormat.  # noqa: E501
        :rtype: int
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this FileFormat.

        The number of lines at the beginning of the file to skip.  # noqa: E501

        :param header: The header of this FileFormat.  # noqa: E501
        :type: int
        """

        self._header = header

    @property
    def footer(self):
        """Gets the footer of this FileFormat.  # noqa: E501

        The number of lines at the end of the file to skip.  # noqa: E501

        :return: The footer of this FileFormat.  # noqa: E501
        :rtype: int
        """
        return self._footer

    @footer.setter
    def footer(self, footer):
        """Sets the footer of this FileFormat.

        The number of lines at the end of the file to skip.  # noqa: E501

        :param footer: The footer of this FileFormat.  # noqa: E501
        :type: int
        """

        self._footer = footer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
