# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MappingExtension(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_reference_id': 'str',
        'ignore_characters': 'list[int]'
    }

    attribute_map = {
        'file_reference_id': 'fileReferenceId',
        'ignore_characters': 'ignoreCharacters'
    }

    def __init__(self, file_reference_id=None, ignore_characters=None):  # noqa: E501
        """MappingExtension - a model defined in Swagger"""  # noqa: E501

        self._file_reference_id = None
        self._ignore_characters = None
        self.discriminator = None

        if file_reference_id is not None:
            self.file_reference_id = file_reference_id
        if ignore_characters is not None:
            self.ignore_characters = ignore_characters

    @property
    def file_reference_id(self):
        """Gets the file_reference_id of this MappingExtension.  # noqa: E501

        The reference URI value returned from the endpoint for uploading files to the Masking Engine. The file should contain a newline separated list of mapping values.  # noqa: E501

        :return: The file_reference_id of this MappingExtension.  # noqa: E501
        :rtype: str
        """
        return self._file_reference_id

    @file_reference_id.setter
    def file_reference_id(self, file_reference_id):
        """Sets the file_reference_id of this MappingExtension.

        The reference URI value returned from the endpoint for uploading files to the Masking Engine. The file should contain a newline separated list of mapping values.  # noqa: E501

        :param file_reference_id: The file_reference_id of this MappingExtension.  # noqa: E501
        :type: str
        """

        self._file_reference_id = file_reference_id

    @property
    def ignore_characters(self):
        """Gets the ignore_characters of this MappingExtension.  # noqa: E501

        The integer ASCII values of characters to ignore in the column data to map  # noqa: E501

        :return: The ignore_characters of this MappingExtension.  # noqa: E501
        :rtype: list[int]
        """
        return self._ignore_characters

    @ignore_characters.setter
    def ignore_characters(self, ignore_characters):
        """Sets the ignore_characters of this MappingExtension.

        The integer ASCII values of characters to ignore in the column data to map  # noqa: E501

        :param ignore_characters: The ignore_characters of this MappingExtension.  # noqa: E501
        :type: list[int]
        """

        self._ignore_characters = ignore_characters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MappingExtension, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MappingExtension):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
