# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MaskingJobScript(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'contents': 'str'
    }

    attribute_map = {
        'name': 'name',
        'contents': 'contents'
    }

    def __init__(self, name=None, contents=None):  # noqa: E501
        """MaskingJobScript - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._contents = None
        self.discriminator = None

        self.name = name
        self.contents = contents

    @property
    def name(self):
        """Gets the name of this MaskingJobScript.  # noqa: E501

        The name of the job SQL script, e.g. 'prescript.sql' or 'postscript.sql'  # noqa: E501

        :return: The name of this MaskingJobScript.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MaskingJobScript.

        The name of the job SQL script, e.g. 'prescript.sql' or 'postscript.sql'  # noqa: E501

        :param name: The name of this MaskingJobScript.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501

        self._name = name

    @property
    def contents(self):
        """Gets the contents of this MaskingJobScript.  # noqa: E501

        The file contents of the job SQL script.  # noqa: E501

        :return: The contents of this MaskingJobScript.  # noqa: E501
        :rtype: str
        """
        return self._contents

    @contents.setter
    def contents(self, contents):
        """Sets the contents of this MaskingJobScript.

        The file contents of the job SQL script.  # noqa: E501

        :param contents: The contents of this MaskingJobScript.  # noqa: E501
        :type: str
        """
        if contents is None:
            raise ValueError("Invalid value for `contents`, must not be `None`")  # noqa: E501

        self._contents = contents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MaskingJobScript, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaskingJobScript):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
