# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PluginObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'object_identifier': 'str',
        'object_name': 'str',
        'object_type': 'str'
    }

    attribute_map = {
        'object_identifier': 'objectIdentifier',
        'object_name': 'objectName',
        'object_type': 'objectType'
    }

    def __init__(self, object_identifier=None, object_name=None, object_type=None):  # noqa: E501
        """PluginObject - a model defined in Swagger"""  # noqa: E501

        self._object_identifier = None
        self._object_name = None
        self._object_type = None
        self.discriminator = None

        if object_identifier is not None:
            self.object_identifier = object_identifier
        if object_name is not None:
            self.object_name = object_name
        if object_type is not None:
            self.object_type = object_type

    @property
    def object_identifier(self):
        """Gets the object_identifier of this PluginObject.  # noqa: E501


        :return: The object_identifier of this PluginObject.  # noqa: E501
        :rtype: str
        """
        return self._object_identifier

    @object_identifier.setter
    def object_identifier(self, object_identifier):
        """Sets the object_identifier of this PluginObject.


        :param object_identifier: The object_identifier of this PluginObject.  # noqa: E501
        :type: str
        """

        self._object_identifier = object_identifier

    @property
    def object_name(self):
        """Gets the object_name of this PluginObject.  # noqa: E501


        :return: The object_name of this PluginObject.  # noqa: E501
        :rtype: str
        """
        return self._object_name

    @object_name.setter
    def object_name(self, object_name):
        """Sets the object_name of this PluginObject.


        :param object_name: The object_name of this PluginObject.  # noqa: E501
        :type: str
        """

        self._object_name = object_name

    @property
    def object_type(self):
        """Gets the object_type of this PluginObject.  # noqa: E501

        The type of plugin object  # noqa: E501

        :return: The object_type of this PluginObject.  # noqa: E501
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this PluginObject.

        The type of plugin object  # noqa: E501

        :param object_type: The object_type of this PluginObject.  # noqa: E501
        :type: str
        """
        allowed_values = ["ALGORITHM", "ALGORITHM_FRAMEWORK"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"  # noqa: E501
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PluginObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PluginObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
