# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SshKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ssh_key_name': 'str'
    }

    attribute_map = {
        'ssh_key_name': 'sshKeyName'
    }

    def __init__(self, ssh_key_name=None):  # noqa: E501
        """SshKey - a model defined in Swagger"""  # noqa: E501

        self._ssh_key_name = None
        self.discriminator = None

        if ssh_key_name is not None:
            self.ssh_key_name = ssh_key_name

    @property
    def ssh_key_name(self):
        """Gets the ssh_key_name of this SshKey.  # noqa: E501

        The name of the SSH key. This field will match the file name of the SSH key as it exists on the file system.  # noqa: E501

        :return: The ssh_key_name of this SshKey.  # noqa: E501
        :rtype: str
        """
        return self._ssh_key_name

    @ssh_key_name.setter
    def ssh_key_name(self, ssh_key_name):
        """Sets the ssh_key_name of this SshKey.

        The name of the SSH key. This field will match the file name of the SSH key as it exists on the file system.  # noqa: E501

        :param ssh_key_name: The ssh_key_name of this SshKey.  # noqa: E501
        :type: str
        """

        self._ssh_key_name = ssh_key_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SshKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SshKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
