# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SystemInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'build': 'str',
        'latest_global_key_reset_time': 'str',
        'patent_numbers': 'list[str]',
        'total_allocated_memory_for_jobs': 'float',
        'total_available_cores': 'int'
    }

    attribute_map = {
        'version': 'version',
        'build': 'build',
        'latest_global_key_reset_time': 'latestGlobalKeyResetTime',
        'patent_numbers': 'patentNumbers',
        'total_allocated_memory_for_jobs': 'totalAllocatedMemoryForJobs',
        'total_available_cores': 'totalAvailableCores'
    }

    def __init__(self, version=None, build=None, latest_global_key_reset_time=None, patent_numbers=None, total_allocated_memory_for_jobs=None, total_available_cores=None):  # noqa: E501
        """SystemInformation - a model defined in Swagger"""  # noqa: E501

        self._version = None
        self._build = None
        self._latest_global_key_reset_time = None
        self._patent_numbers = None
        self._total_allocated_memory_for_jobs = None
        self._total_available_cores = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if build is not None:
            self.build = build
        if latest_global_key_reset_time is not None:
            self.latest_global_key_reset_time = latest_global_key_reset_time
        if patent_numbers is not None:
            self.patent_numbers = patent_numbers
        if total_allocated_memory_for_jobs is not None:
            self.total_allocated_memory_for_jobs = total_allocated_memory_for_jobs
        if total_available_cores is not None:
            self.total_available_cores = total_available_cores

    @property
    def version(self):
        """Gets the version of this SystemInformation.  # noqa: E501

        The current version of the Masking Engine.  # noqa: E501

        :return: The version of this SystemInformation.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this SystemInformation.

        The current version of the Masking Engine.  # noqa: E501

        :param version: The version of this SystemInformation.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def build(self):
        """Gets the build of this SystemInformation.  # noqa: E501

        The current build of the Masking Engine.  # noqa: E501

        :return: The build of this SystemInformation.  # noqa: E501
        :rtype: str
        """
        return self._build

    @build.setter
    def build(self, build):
        """Sets the build of this SystemInformation.

        The current build of the Masking Engine.  # noqa: E501

        :param build: The build of this SystemInformation.  # noqa: E501
        :type: str
        """

        self._build = build

    @property
    def latest_global_key_reset_time(self):
        """Gets the latest_global_key_reset_time of this SystemInformation.  # noqa: E501

        The latest time the global encryption key has been regenerated.  # noqa: E501

        :return: The latest_global_key_reset_time of this SystemInformation.  # noqa: E501
        :rtype: str
        """
        return self._latest_global_key_reset_time

    @latest_global_key_reset_time.setter
    def latest_global_key_reset_time(self, latest_global_key_reset_time):
        """Sets the latest_global_key_reset_time of this SystemInformation.

        The latest time the global encryption key has been regenerated.  # noqa: E501

        :param latest_global_key_reset_time: The latest_global_key_reset_time of this SystemInformation.  # noqa: E501
        :type: str
        """

        self._latest_global_key_reset_time = latest_global_key_reset_time

    @property
    def patent_numbers(self):
        """Gets the patent_numbers of this SystemInformation.  # noqa: E501

        The patent numbers for the Masking Engine.  # noqa: E501

        :return: The patent_numbers of this SystemInformation.  # noqa: E501
        :rtype: list[str]
        """
        return self._patent_numbers

    @patent_numbers.setter
    def patent_numbers(self, patent_numbers):
        """Sets the patent_numbers of this SystemInformation.

        The patent numbers for the Masking Engine.  # noqa: E501

        :param patent_numbers: The patent_numbers of this SystemInformation.  # noqa: E501
        :type: list[str]
        """

        self._patent_numbers = patent_numbers

    @property
    def total_allocated_memory_for_jobs(self):
        """Gets the total_allocated_memory_for_jobs of this SystemInformation.  # noqa: E501

        The total memory size in MB allocated for running jobs on the Masking Engine.  # noqa: E501

        :return: The total_allocated_memory_for_jobs of this SystemInformation.  # noqa: E501
        :rtype: float
        """
        return self._total_allocated_memory_for_jobs

    @total_allocated_memory_for_jobs.setter
    def total_allocated_memory_for_jobs(self, total_allocated_memory_for_jobs):
        """Sets the total_allocated_memory_for_jobs of this SystemInformation.

        The total memory size in MB allocated for running jobs on the Masking Engine.  # noqa: E501

        :param total_allocated_memory_for_jobs: The total_allocated_memory_for_jobs of this SystemInformation.  # noqa: E501
        :type: float
        """

        self._total_allocated_memory_for_jobs = total_allocated_memory_for_jobs

    @property
    def total_available_cores(self):
        """Gets the total_available_cores of this SystemInformation.  # noqa: E501

        The total number of processors available to the Masking Engine.  # noqa: E501

        :return: The total_available_cores of this SystemInformation.  # noqa: E501
        :rtype: int
        """
        return self._total_available_cores

    @total_available_cores.setter
    def total_available_cores(self, total_available_cores):
        """Sets the total_available_cores of this SystemInformation.

        The total number of processors available to the Masking Engine.  # noqa: E501

        :param total_available_cores: The total_available_cores of this SystemInformation.  # noqa: E501
        :type: int
        """

        self._total_available_cores = total_available_cores

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
